### ISSUE TITLE
The flashcard creator tries to import a (other) word which is already in the database

### ISSUE THREAD

**Issue by arobirosa** [arobirosa/learn-bulgarian-flashcard-creator#21]
**Describe the bug**
When importing the attached file, a database error is thrown which breaks the processing of the file

**To Reproduce**
1. Import the attached file
2. Confirm the translations when asked

**Expected behavior**
The file can be processed until the end

**Log entries**
2024-02-25 20:59:21,406 - flashcardcreator.affix - DEBUG - Derivative forms of the verb {'сег.вр., 1л., ед.ч.': 'твърдя', 'сег.вр., 2л., ед.ч.': 'твърдиш', 'сег.вр., 3л., мн.ч.': 'твърдят', 'мин.св.вр., 1л., ед.ч.': 'твърдях', 'мин.св.вр., 2л., ед.ч.': 'твърдя', 'мин.несв.вр., 1л., ед.ч.': 'твърдях', 'мин.несв.вр., 2л., ед.ч.': 'твърдеше', 'повелително наклонение, ед.ч.': 'твърди', 'повелително наклонение, мн.ч.': 'твърдете', 'мин.страд.прич. ср.р.': 'твърдяно', 'мин.деят.св.прич. м.р.': 'твърдял', 'мин.деят.св.прич. м.р. пълен член': 'твърделият', 'мин.деят.св.прич. ж.р.': 'твърдяла', 'мин.деят.св.прич. ср.р.': 'твърдяло', 'мин.деят.св.прич. мн.ч.': 'твърдели', 'мин.деят.несв.прич. м.р.': 'твърдял', 'мин.деят.несв.прич. мн.ч.': 'твърдели', 'сег.деят.прич. м.р.': 'твърдящ', 'деепричастие': 'твърдейки'}
2024-02-25 20:59:21,407 - flashcardcreator.main - INFO - Adding a flashcard for the verb твърдя to all required tables
Traceback (most recent call last):
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/start.py", line 118, in <module>
    import_words_from_text_file(global_arguments.input_file_path,
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 761, in import_words_from_text_file
    if not found_word.create_flashcard():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 336, in create_flashcard
    return self._add_row_to_flashcard_database(derivative_forms_to_study)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 443, in _add_row_to_flashcard_database
    _insert_verb(flashcard_database, derivative_forms_to_study,
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 109, in _insert_verb
    insert_participles_with_cursor(db_cursor, verb_participles,
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/database.py", line 97, in insert_participles_with_cursor
    insert_other_word_type_with_cursor(db_cursor, word_fields)
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/database.py", line 82, in insert_other_word_type_with_cursor
    db_cursor.execute('''
sqlite3.IntegrityError: UNIQUE constraint failed: otherWordTypes.word

Process finished with exit code 1

**Screenshots**
None.

**Additional context**
There isn't enough logging. I will add it in #13 

Imported file:
[20240225newWords1.txt](https://github.com/arobirosa/learn-bulgarian-flashcard-creator/files/14397548/20240225newWords1.txt)

**Comment by arobirosa** [comment]
the code fails when adding the participle of the verb:

```
2024-02-26 09:45:04,461 - flashcardcreator.main - INFO - Adding a flashcard for the verb заваля to all required tables
Traceback (most recent call last):
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/start.py", line 118, in <module>
    import_words_from_text_file(global_arguments.input_file_path,
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 770, in import_words_from_text_file
    if not found_word.create_flashcard():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 343, in create_flashcard
    return self._add_row_to_flashcard_database(derivative_forms_to_study)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 450, in _add_row_to_flashcard_database
    _insert_verb(flashcard_database, derivative_forms_to_study,
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/main.py", line 110, in _insert_verb
    insert_participles_with_cursor(db_cursor, verb_participles,
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/database.py", line 97, in insert_participles_with_cursor
    insert_other_word_type_with_cursor(db_cursor, word_fields)
  File "/home/arobirosa/no_backup/python/flashcard-creator/flashcardCreator/flashcardcreator/database.py", line 82, in insert_other_word_type_with_cursor
    db_cursor.execute('''
sqlite3.IntegrityError: UNIQUE constraint failed: otherWordTypes.word

Process finished with exit code 1

```

**Comment by arobirosa** [comment]
The participles are duplicated in the grammatical database:
`{'мин.деят.св.прич. м.р.': 'завалял', 'мин.деят.св.прич. мн.ч.': 'завалели', 'мин.деят.несв.прич. м.р.': 'завалял'}`

**Comment by arobirosa** [comment]
Now the particles which have multiple derivative forms can be imported. The derivative forms are combined:

![image](https://github.com/arobirosa/learn-bulgarian-flashcard-creator/assets/19760446/66db7561-c823-4dfb-ba94-e14adbf8475d)

**Comment by arobirosa** [comment]
I created a new test, document the combination of particles and corrected the flashcard database.

**Comment by arobirosa** [comment]
The corrections were done on the branch of #13
